### ISSUE TITLE
Left Click Drop Bug?

### ISSUE THREAD

**Issue by Smiteyou2** [redrumze/zom-external-plugins#12]
Left click drop does not work with Olive oil(1), (2), (3), or (4). 
![Olive oil(1)](https://user-images.githubusercontent.com/80333743/110479641-a0c99980-80b3-11eb-809b-68adc49db1cd.PNG)

**Comment by redrumze** [comment]
Appears to work normally for me. 

![image](https://user-images.githubusercontent.com/14265490/110580662-1c205f00-8137-11eb-92a3-9c10f0f2fa21.jpeg)
