### ISSUE TITLE
commas perhaps

### ISSUE THREAD

**Issue by Oiuyo** [redrumze/zom-external-plugins#13]
so instead of 1000, it would be 1,000. This is useful for larger numbers where 10,000,000 is much easier to read than 10000000

**Comment by redrumze** [comment]
Oh I complete forgot about number formatting...

Whoops. It'll be fixed soon.

**Comment by redrumze** [comment]
https://github.com/runelite/plugin-hub/pull/1369 This will fix the issue when it is merged.

**Comment by Oiuyo** [comment]
Thank you very much, i love this plugin!
