### ISSUE TITLE
Construction QOL: Ignore when in cox

### ISSUE THREAD

**Issue by Newbcake** [redrumze/zom-external-plugins#39]
Currently it swaps inputs for upgrading the storage chest at cox, I think this is undesirable.

Would be nice to have the plugin ignore this chest, can probably easily by done by checking the region the player like watchdog does: https://github.com/adamk33n3r/runelite-watchdog/blob/master/src/main/java/com/adamk33n3r/runelite/watchdog/Region.java#L16-L24

**Comment by JZomDev** [comment]
Oh. Yes. 

I'll fix this.

**Comment by JZomDev** [comment]
It is fixed in https://github.com/runelite/plugin-hub/pull/6115

**Comment by Newbcake** [comment]
Thanks!

A side effect of this implementation is that it will now no longer work during mahogany homes, I personally don't care about this but it's something to consider. I'm not sure if there are any other places in the game that use the construction menu widget, I know most quests that involve construction don't, but the miniquest daddy's home does.

**Comment by JZomDev** [comment]
How does mahogany homes work? I thought there was no options for building. You just build the exact item(s)

Considering that you're not always building option 1,2,3,4 or what ever at mahogany homes, i think it's fine if it doesn't work there. Unless it's meant to always be the same number for every task. 

I'll wait for someone to complain about mahogany homes I think and then fix it with a region check, idk if those users will care.

**Comment by Newbcake** [comment]
Timestamped video from youtube for reference: https://youtu.be/Xh-Pm-BXtbo?t=288

It's essentially the same as POH construction, you're always pressing the same number corresponding to what tier of contract you're doing. So let's say you're doing expert contracts which require mahogany logs, you will always press '4' in the widget but if you were doing adept contracts then you would be pressing '3' for teak.

I don't think these users would care much, but you might expect a report in the future from someone why this plugin is 'eating' their inputs in mahogany homes.

EIther way, happy with the quick fix. Thanks!!!
