### ISSUE TITLE
AFK GOTR plugin out of date

### ISSUE THREAD

**Issue by IsekaiVictim** [redrumze/zom-external-plugins#45]
All locations where it lists the 150 point threshold need to be updated to the new 300 point threshold

**Comment by JZomDev** [comment]
I don't think I'm going to update it but instead disable it. The plugin only existed to force jagex to fix the minigame because afk players ruined the game. Now that it's more active it's not a problem.

**Comment by IsekaiVictim** [comment]
I really wasn't expecting that response lmao. Off topic from the plugin, but
Are games ending faster with the changes due to less people afking?
Is the 300 point threshold that bad for afking, considering the increased points earned from always being able to turn in charged cells?
I would have thought not much had changed, with the threshold only being 300 points, but i havent done gotr since they made the change

**Comment by JZomDev** [comment]
> Are games ending faster with the changes due to less people afking?

I think there is just more people doing them on some worlds as there is no player limit. They end very fast.

> Is the 300 point threshold that bad for afking, considering the increased points earned from always being able to turn in charged cells?

With a 150 point limit you could get 150 points with a single 85 lap of the mega pouch, you'd RC 66 ess at a minimum, giving you 132 points and if you did an overloaded cell you would hit 150 points. 

Back when this plugin was first made you would do a full RC lap and go back to mining and get 30k RC xp/hr + no limit of mining xp, but with recent updates you need to do 2 or 3 full RC laps and you no longer get infinite mining xp, it caps after 250 resources collected. 

Considering you can only do maybe 6 or 7 full RC laps(Life cycle of a typical game now) 

> Life cycle of the game being: 
 Mine until 20 seconds left then craft. 
 portal appears
 craft more runes, mine until portal appears and repeat line 2/3 until minigame is done. 
 
You're getting maybe 3 or 3.5 full cycles for 6 or 7 full runecraft laps.

I don't know if I think it's good to AFK given that you need to do a min 2 laps (if you're 85 rc + mega pouch) or 3/4 laps if you don't considering that the game lasts 6 or 7 full cycles anyways. Being afk for half the time with no bonus xp for mining is a bit bad.


I only created this plugin to make the game play loop/game experience worse and I wanted people to use and abuse it until Jagex fixed it. With a higher limit for xp drop and more players in a lobby with shorter games, it's harder to be afk for the big xp drop and it's harder to make the game lose anyways.

**Comment by Committing** [comment]
needs fixing

**Comment by Committing** [comment]
Trash owner

**Comment by JZomDev** [comment]
> Trash owner

Read my reason for turning it off above, i'm glad you cloned my fork though - you clearly don't understand why.

**Comment by Committing** [comment]
I already fixed ur plugin and u were useless

**Comment by JZomDev** [comment]
> I already fixed ur plugin and u were useless

I didn't say the plugin wasn't able to be fixed, I said I will not be fixing it as it doesn't need to be fixed and should be disabled again, but again - you don't understand why. I don't expect an AI developer to know anything at all and I am frankly surprised you know how to compile any code at all, but congratulations on changing the value of "150" to "300" in the project, really well done.
