### ISSUE TITLE
Construction QOL Suggestion

### ISSUE THREAD

**Issue by Tree445** [redrumze/zom-external-plugins#46]
Expand the Input/Output keys to other keys, namely Spacebar. 

Currently mixing this plugin with Keybind Remapping, allows for just using 1-9 as a single keybind for all construction needs, but it would be a slightly better QOL if used with Dialogue Option Rebinder to make Spacebar the primary keybind instead.

**Comment by JZomDev** [comment]
The purpose is to switch the numbers not add any keybind. 

You never need to click space when using this plugin anyways.
