### ISSUE TITLE
Two references to 'utilties' instead of 'utilities'

### ISSUE THREAD

**Issue by asmith-personal** [redrumze/zom-external-plugins#8]
[runelite-plugin.properties#L1](https://github.com/JZomerlei/zom-external-plugins/blob/457b8b0d523a84fe76c0dad598c12629bcb98fd0/runelite-plugin.properties#L1)
[runelite-plugin.properties#L5](https://github.com/JZomerlei/zom-external-plugins/blob/457b8b0d523a84fe76c0dad598c12629bcb98fd0/runelite-plugin.properties#L5)

**Comment by redrumze** [comment]
Fixed. Sorry about delay... Sort of not a priority haha
